-- 1. Crear tabla de Productos
CREATE TABLE public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC NOT NULL,
  image TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Insertar los productos iniciales de prueba
INSERT INTO public.products (name, description, price, image)
VALUES 
  ('Producto Estrella 2', 'Este es un producto maravilloso de la línea de Farmasi con propiedades increíbles para tu cuidado personal. Te encantarán los resultados desde el primer día de uso continuado.', 250.00, '/Productos/2.jpeg'),
  ('Producto Estrella 3', 'Este es un producto maravilloso de la línea de Farmasi con propiedades increíbles para tu cuidado personal. Te encantarán los resultados desde el primer día de uso continuado.', 250.00, '/Productos/3.jpeg'),
  ('Producto Estrella 4', 'Este es un producto maravilloso de la línea de Farmasi con propiedades increíbles para tu cuidado personal. Te encantarán los resultados desde el primer día de uso continuado.', 250.00, '/Productos/4.jpeg'),
  ('Producto Estrella 5', 'Este es un producto maravilloso de la línea de Farmasi con propiedades increíbles para tu cuidado personal. Te encantarán los resultados desde el primer día de uso continuado.', 250.00, '/Productos/5.jpeg'),
  ('Producto Estrella 6', 'Este es un producto maravilloso de la línea de Farmasi con propiedades increíbles para tu cuidado personal. Te encantarán los resultados desde el primer día de uso continuado.', 250.00, '/Productos/6.jpeg'),
  ('Producto Estrella 7', 'Este es un producto maravilloso de la línea de Farmasi con propiedades increíbles para tu cuidado personal. Te encantarán los resultados desde el primer día de uso continuado.', 250.00, '/Productos/7.jpeg');

-- 3. Habilitar políticas de seguridad para que cualquiera pueda leer, pero solo quien acceda haga cambios.
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir lectura publica" ON public.products FOR SELECT USING (true);
CREATE POLICY "Permitir hacer updates y cambios" ON public.products FOR ALL USING (true);

-- 4. AGREGAR CATEGORÍAS (Hombres / Mujeres)
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'women';

-- 5. SOPORTE MULTI-FOTOS
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS extra_images TEXT[] DEFAULT '{}';

-- 6. SISTEMA DE MULTI-ADMINISTRADORES
CREATE TABLE IF NOT EXISTS public.admins (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Desactivar políticas restrictivas para admins igual que en productos
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir acceso admins a usuarios logueados" ON public.admins FOR ALL USING (true);
